apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ${AWS_REGION}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-ecr-repo-jocasmen:latest
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes the service outside the cluster (assumes you're running on a cloud provider that supports LoadBalancer)

